<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FurnitureAuthoring.Domain\FurnitureAuthoring.Domain.csproj" />
    <ProjectReference Include="..\FurnitureAuthoring.Contracts\FurnitureAuthoring.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
